### ISSUE TITLE
The Cheart Left-clicking will freeze the screen, but it will not be unresponsive

### ISSUE THREAD

**Issue by GuJian502** [VapuClient/Cheart-Issue-Tracker#1]
**错误信息**
错误窗口，异常堆栈，错误码等信息

**异常日志**
可以在游戏运行目录的logs文件夹找到，文件名为latest.log

**环境**
请提供以下信息
1. 游戏版本
2. 客户端版本
3. 注入器版本
4. java版本
5. 操作系统（例如Windows 11）
6. 如果是网易我的世界，请提供服务器名字

**Comment by GuJian502** [comment]
[latest.log](https://github.com/user-attachments/files/17237790/latest.log)
游戏版本 1.18.1
客户端版本 1.18.1
注入器版本 Cheart lastes
java版本 jre17
操作系统（例如Windows 11）Windows 11
如果是网易我的世界，请提供服务器名字 布吉岛

**Comment by zwwc** [comment]
fixed in latest update
