### ISSUE TITLE
在win11的24h2的26100.1742中当进度条达到67%时 注入器会直接崩溃 但是游戏并没有崩溃

### ISSUE THREAD

**Issue by GuJian502** [VapuClient/Cheart-Issue-Tracker#10]
**错误信息**
[latest.log](https://github.com/user-attachments/files/17265754/latest.log)

**环境**
请提供以下信息
1. 游戏版本 1.18.1
2. 客户端版本 1.18.1
3. 注入器版本 latest
4. java版本 jdk17
5. 操作系统（例如Windows 11）win11
6. 如果是网易我的世界，请提供服务器名字 布吉岛

**Comment by zwwc** [comment]
您好，请尝试禁用所有防病毒软件，然后重试。
