### ISSUE TITLE
ClickGUI被错误绑定为NONE

### ISSUE THREAD

**Issue by Creependerman** [VapuClient/Cheart-Issue-Tracker#11]
**问题描述**
客户端中的clickgui错误绑定为none且无法重新绑定。

**复现方法**
鼠标中键选项，按下RSHIFT

**客户端版本**
选项：1.18.1、1.18.2

**错误信息**
如果有任何错误信息，请提供

**你是否确定你已经使用了最新版本的客户端**
选项：是

**Comment by zwwc** [comment]
您好，请尝试Ctrl+Alt+Insert热键，可以强制打开 GUI
