### ISSUE TITLE
添加一些

### ISSUE THREAD

**Issue by ImNoiq123** [VapuClient/Cheart-Issue-Tracker#2]
**描述**
添加弓箭自瞄(BowAimBot)，视觉抛物线，辅助瞄准(AimAssist)，自动点击(AutoClick)，自动工具(AutoTool)
为了安全起见可以为Killaura添加客户端转头(虽然可能没那么安全)
BedAura只有在床没方块围着的时候才能正常生效，被方块围着吉吉岛回弹请勿隔墙拆床，希望改进

**参考**
大部分功能在水影就有

**Comment by zwwc** [comment]
合法功能不在计划中，AutoTool 已添加，客户端旋转渲染在图表中调用“Rotations”。BedAura 将很快修复。

**Comment by BigLOLK** [comment]
那可以添加BowAimBot吗，对于我这个喜欢打逃离暗区的手残党来说真的很需要

**Comment by ImNoiq123** [comment]
> 那可以添加BowAimBot吗，对于我这个喜欢打逃离暗区的手残党来说真的很需要
可以添加notification这个视觉模块吗？
