### ISSUE TITLE
点击左键后出现保存世界中

### ISSUE THREAD

**Issue by cxn01111** [VapuClient/Cheart-Issue-Tracker#5]
**错误信息**
没有任何错误信息，没有打开任何功能

**异常日志**

[latest.log](https://github.com/user-attachments/files/17239275/latest.log)
 

**环境**
请提供以下信息
1. 1.18.1
2. 1.18
3. 最新
4. jdk17
5. Windows 11
6. 布吉岛

**Comment by zwwc** [comment]
Fixed in latest update
