### ISSUE TITLE
在注入成功后无法读取和创建 config和背包整理的背包预设

### ISSUE THREAD

**Issue by GuJian502** [VapuClient/Cheart-Issue-Tracker#6]
**问题描述**
简单描述这个问题

**复现方法**
简述这个问题是如何复现的，也就是做什么会导致这个问题

**客户端版本**
选项：1.18.1、1.18.2

**错误信息**
如果有任何错误信息，请提供

**你是否确定你已经使用了最新版本的客户端**
选项：是/否

**Comment by GuJian502** [comment]
1.18.1
已使用最新客户端

**Comment by zwwc** [comment]
您好，我们已经修复这个问题在最新版本。
