### ISSUE TITLE
lagrange[staffcheck]

### ISSUE THREAD

**Issue by zone1889** [VapuClient/Cheart-Issue-Tracker#8]
**描述**
lagrange[staffcheck]
我们需要一个带有检查是否有客服监管的fakelag是否可以绕过

**参考**
如果已经有客户端实现了此功能，或者有关于这个功能的视频，请附带，如果此功能过于普遍（例如nofall）可以不附带

**Comment by zwwc** [comment]
员工在Heypixel是无法被检测的
