### ISSUE TITLE
添加一些功能

### ISSUE THREAD

**Issue by ImNoiq123** [VapuClient/Cheart-Issue-Tracker#9]
**描述**
添加BowAimBot和改进killaura，有些时候总感觉killaura打不到人就被击飞或打死了
视觉类添加Notification，我这种眼瞎的一般不看Arraylist

**Comment by zwwc** [comment]
你好，事实上，cheart 在 grim 反作弊下已经拥有最好的 killaura（具有最严格的目标碰撞框切割），Bow 瞄准机器人不会绕过 heypixel，因为 Heypixel 的一些反作弊功能可以检测到它，通知已经添加。
